/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    'solution-plans': SolutionPlan;
    'portfolio-projects': PortfolioProject;
    partners: Partner;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'solution-plans': SolutionPlansSelect<false> | SolutionPlansSelect<true>;
    'portfolio-projects': PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'he') | ('en' | 'ru' | 'he')[];
  globals: {
    header: Header;
    hero: Hero;
    'services-section': ServicesSection;
    'case-studies': CaseStudy;
    'solutions-section': SolutionsSection;
    'faq-section': FaqSection;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'services-section': ServicesSectionSelect<false> | ServicesSectionSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'solutions-section': SolutionsSectionSelect<false> | SolutionsSectionSelect<true>;
    'faq-section': FaqSectionSelect<false> | FaqSectionSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ru' | 'he';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            title?: string | null;
            ctaText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
        | {
            words?:
              | {
                  word: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'wordStackBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL for the service page, e.g. "design-branding" → /services/design-branding. Also used by the home card “more” link.
   */
  slug?: string | null;
  /**
   * Display number, e.g. "01"
   */
  number?: string | null;
  /**
   * Card image/video. Recommended: 1600×1000 px (16:10), minimum 1200 px wide. Images are stored in original quality without upload compression. MP4/WebM videos autoplay muted.
   */
  image?: (number | null) | Media;
  /**
   * Wide header image/video for /services/[slug]. Recommended: 1920×300 px, minimum 1600×250 px. Images are stored in original quality without upload compression. Falls back to the card media.
   */
  heroMedia?: (number | null) | Media;
  /**
   * Currency used for all packages and prices on this service page
   */
  currency: 'USD' | 'ILS' | 'EUR';
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Short intro on the service detail page (rich text)
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Detailed description on the service page (rich text)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  offerings?:
    | {
        name: string;
        description?: string | null;
        /**
         * e.g. "2 500"
         */
        price: string;
        /**
         * e.g. "from" / "от"
         */
        pricePrefix?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If empty, the page title and intro text are used for search engines and social previews.
   */
  seo?: {
    /**
     * Meta title. Example: "Design & Branding | Erythro.ai"
     */
    title?: string | null;
    /**
     * Meta description (recommended up to ~160 characters).
     */
    description?: string | null;
  };
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-plans".
 */
export interface SolutionPlan {
  id: number;
  title: string;
  /**
   * Stable id / order URL, e.g. "business-automation" → /order/business-automation
   */
  slug?: string | null;
  /**
   * Main price value, e.g. "14 999" or "0"
   */
  price: string;
  /**
   * Currency shown next to the price on the site and order page
   */
  currency: 'ILS' | 'USD' | 'EUR';
  /**
   * Optional prefix, e.g. "from" / "от"
   */
  pricePrefix?: string | null;
  /**
   * Optional old/struck-through price
   */
  originalPrice?: string | null;
  /**
   * Show installment note marker (*)
   */
  priceNote?: boolean | null;
  /**
   * Highlight this plan as recommended
   */
  featured?: boolean | null;
  /**
   * Fill "label" + "value" for a two-column row, OR "full" for a single full-width row.
   */
  features?:
    | {
        label?: string | null;
        value?: string | null;
        full?: string | null;
        id?: string | null;
      }[]
    | null;
  disclaimer?: string | null;
  /**
   * Subtitle on the order page under the plan title
   */
  subtitle?: string | null;
  /**
   * Green promo callout on the order page
   */
  promo?: string | null;
  /**
   * Optional. If empty, defaults (pay in full / 12 payments when priceNote) are used.
   */
  periods?:
    | {
        /**
         * e.g. "full" or "12"
         */
        periodId: string;
        label: string;
        /**
         * 1 = one-time; 12 = split into months for display
         */
        months?: number | null;
        discountPercent?: number | null;
        id?: string | null;
      }[]
    | null;
  addons?:
    | {
        /**
         * Stable id, e.g. "priority-support"
         */
        addonId: string;
        name: string;
        description?: string | null;
        /**
         * Amount in the plan currency (number)
         */
        price: number;
        recommended?: boolean | null;
        /**
         * Always include this add-on in the order. Customers cannot deselect it.
         */
        mandatory?: boolean | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If empty, the page title and intro text are used for search engines and social previews.
   */
  seo?: {
    /**
     * Meta title. Example: "Design & Branding | Erythro.ai"
     */
    title?: string | null;
    /**
     * Meta description (recommended up to ~160 characters).
     */
    description?: string | null;
  };
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects".
 */
export interface PortfolioProject {
  id: number;
  /**
   * URL segment, e.g. "ai-lead-qualifier" → /portfolio/ai-lead-qualifier
   */
  slug: string;
  title: string;
  category: 'ai' | 'crm' | 'websites' | 'landing' | 'apps' | 'other';
  categoryLabel: string;
  /**
   * Short card description on /portfolio
   */
  description: string;
  /**
   * Hero summary on the project page
   */
  summary: string;
  /**
   * e.g. "2025" or "2024 — 2025"
   */
  date?: string | null;
  client?: string | null;
  /**
   * Optional external project URL
   */
  link?: string | null;
  stack?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Thumbnail on the portfolio grid
   */
  cardImage?: (number | null) | Media;
  /**
   * Full-bleed hero image or video
   */
  heroMedia?: (number | null) | Media;
  body?:
    | {
        heading?: string | null;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If empty, the page title and intro text are used for search engines and social previews.
   */
  seo?: {
    /**
     * Meta title. Example: "Design & Branding | Erythro.ai"
     */
    title?: string | null;
    /**
     * Meta description (recommended up to ~160 characters).
     */
    description?: string | null;
  };
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Optional external link
   */
  url?: string | null;
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  /**
   * Site language the visitor used
   */
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'solution-plans';
        value: number | SolutionPlan;
      } | null)
    | ({
        relationTo: 'portfolio-projects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              ctaText?: T;
              id?: T;
              blockName?: T;
            };
        wordStackBlock?:
          | T
          | {
              words?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  number?: T;
  image?: T;
  heroMedia?: T;
  currency?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  summary?: T;
  description?: T;
  offerings?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        pricePrefix?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-plans_select".
 */
export interface SolutionPlansSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  price?: T;
  currency?: T;
  pricePrefix?: T;
  originalPrice?: T;
  priceNote?: T;
  featured?: T;
  features?:
    | T
    | {
        label?: T;
        value?: T;
        full?: T;
        id?: T;
      };
  disclaimer?: T;
  subtitle?: T;
  promo?: T;
  periods?:
    | T
    | {
        periodId?: T;
        label?: T;
        months?: T;
        discountPercent?: T;
        id?: T;
      };
  addons?:
    | T
    | {
        addonId?: T;
        name?: T;
        description?: T;
        price?: T;
        recommended?: T;
        mandatory?: T;
        note?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  categoryLabel?: T;
  description?: T;
  summary?: T;
  date?: T;
  client?: T;
  link?: T;
  stack?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  cardImage?: T;
  heroMedia?: T;
  body?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        /**
         * e.g. #services
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary call-to-action label
   */
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  preHeading?: string | null;
  mainHeading?: string | null;
  subtext?: string | null;
  /**
   * "Find out more" button label
   */
  ctaFind?: string | null;
  /**
   * Optional hero background image
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Rotating hero headlines (motion text). Leave empty to use the default phrases from code.
   */
  words?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section".
 */
export interface ServicesSection {
  id: number;
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  startCTA?: string | null;
  priceLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  preTitle?: string | null;
  subtitle?: string | null;
  cardTitle?: string | null;
  cardCategory?: string | null;
  cardDescription?: string | null;
  cardCTA?: string | null;
  /**
   * Text link under the video banner, e.g. "View All Projects" (arrows are added in UI)
   */
  viewAllProjects?: string | null;
  /**
   * Desktop banner video (1024px+). Shown instead of the static default when set.
   */
  bannerVideo?: (number | null) | Media;
  /**
   * Mobile banner video (under 1024px). Falls back to the desktop video when empty.
   */
  bannerVideoMobile?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-section".
 */
export interface SolutionsSection {
  id: number;
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section".
 */
export interface FaqSection {
  id: number;
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  /**
   * FAQ accordion items. Drag to reorder.
   */
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  ctaHeadingLine1?: string | null;
  ctaHeadingLine2?: string | null;
  ctaButton?: string | null;
  companyTitle?: string | null;
  companyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactTitle?: string | null;
  emailLabel?: string | null;
  phoneLabel?: string | null;
  locationLabel?: string | null;
  locationValue?: string | null;
  copyright?: string | null;
  legalLinks?:
    | {
        /**
         * Stable id, e.g. privacy
         */
        key?: string | null;
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * e.g. erythro.ai@gmail.com
   */
  email?: string | null;
  /**
   * Raw phone for tel: link, e.g. +972509312746
   */
  phone?: string | null;
  /**
   * Formatted phone shown to users
   */
  phoneDisplay?: string | null;
  /**
   * Facebook URL
   */
  facebook?: string | null;
  /**
   * TikTok URL
   */
  tiktok?: string | null;
  cookieMessage?: string | null;
  cookieAccept?: string | null;
  cookieDecline?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Social share image (1200x630 recommended)
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  subtext?: T;
  ctaFind?: T;
  backgroundImage?: T;
  words?:
    | T
    | {
        word?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section_select".
 */
export interface ServicesSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  startCTA?: T;
  priceLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  preTitle?: T;
  subtitle?: T;
  cardTitle?: T;
  cardCategory?: T;
  cardDescription?: T;
  cardCTA?: T;
  viewAllProjects?: T;
  bannerVideo?: T;
  bannerVideoMobile?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-section_select".
 */
export interface SolutionsSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section_select".
 */
export interface FaqSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaHeadingLine1?: T;
  ctaHeadingLine2?: T;
  ctaButton?: T;
  companyTitle?: T;
  companyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactTitle?: T;
  emailLabel?: T;
  phoneLabel?: T;
  locationLabel?: T;
  locationValue?: T;
  copyright?: T;
  legalLinks?:
    | T
    | {
        key?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  phoneDisplay?: T;
  facebook?: T;
  tiktok?: T;
  cookieMessage?: T;
  cookieAccept?: T;
  cookieDecline?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}