/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  text,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['en', 'ru', 'he'])
export const enum_services_currency = pgEnum('enum_services_currency', ['USD', 'ILS', 'EUR'])
export const enum_solution_plans_currency = pgEnum('enum_solution_plans_currency', [
  'ILS',
  'USD',
  'EUR',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const pages_blocks_hero_block = pgTable(
  'pages_blocks_hero_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_hero_block_order_idx').on(columns._order),
    index('pages_blocks_hero_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_hero_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_hero_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_hero_block_locales = pgTable(
  'pages_blocks_hero_block_locales',
  {
    title: varchar('title'),
    ctaText: varchar('cta_text').default("LET'S TALK..."),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('pages_blocks_hero_block_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_hero_block.id],
      name: 'pages_blocks_hero_block_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_word_stack_block_words = pgTable(
  'pages_blocks_word_stack_block_words',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    _locale: enum__locales('_locale').notNull(),
    id: varchar('id').primaryKey(),
    word: varchar('word').notNull(),
  },
  (columns) => [
    index('pages_blocks_word_stack_block_words_order_idx').on(columns._order),
    index('pages_blocks_word_stack_block_words_parent_id_idx').on(columns._parentID),
    index('pages_blocks_word_stack_block_words_locale_idx').on(columns._locale),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_word_stack_block.id],
      name: 'pages_blocks_word_stack_block_words_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_word_stack_block = pgTable(
  'pages_blocks_word_stack_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_word_stack_block_order_idx').on(columns._order),
    index('pages_blocks_word_stack_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_word_stack_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_word_stack_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const services_features = pgTable(
  'services_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('services_features_order_idx').on(columns._order),
    index('services_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services.id],
      name: 'services_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const services_features_locales = pgTable(
  'services_features_locales',
  {
    feature: varchar('feature').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('services_features_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services_features.id],
      name: 'services_features_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const services_offerings = pgTable(
  'services_offerings',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    price: varchar('price').notNull(),
  },
  (columns) => [
    index('services_offerings_order_idx').on(columns._order),
    index('services_offerings_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services.id],
      name: 'services_offerings_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const services_offerings_locales = pgTable(
  'services_offerings_locales',
  {
    name: varchar('name').notNull(),
    description: varchar('description'),
    pricePrefix: varchar('price_prefix'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('services_offerings_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services_offerings.id],
      name: 'services_offerings_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const services = pgTable(
  'services',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug'),
    number: varchar('number'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    heroMedia: integer('hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    currency: enum_services_currency('currency').notNull().default('USD'),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('services_slug_idx').on(columns.slug),
    index('services_image_idx').on(columns.image),
    index('services_hero_media_idx').on(columns.heroMedia),
    index('services_updated_at_idx').on(columns.updatedAt),
    index('services_created_at_idx').on(columns.createdAt),
  ],
)

export const services_locales = pgTable(
  'services_locales',
  {
    title: varchar('title').notNull(),
    summary: jsonb('summary'),
    description: jsonb('description'),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('services_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services.id],
      name: 'services_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans_features = pgTable(
  'solution_plans_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('solution_plans_features_order_idx').on(columns._order),
    index('solution_plans_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans.id],
      name: 'solution_plans_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans_features_locales = pgTable(
  'solution_plans_features_locales',
  {
    label: varchar('label'),
    value: varchar('value'),
    full: varchar('full'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('solution_plans_features_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans_features.id],
      name: 'solution_plans_features_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans_periods = pgTable(
  'solution_plans_periods',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    periodId: varchar('period_id').notNull(),
    months: numeric('months', { mode: 'number' }).default(1),
    discountPercent: numeric('discount_percent', { mode: 'number' }).default(0),
  },
  (columns) => [
    index('solution_plans_periods_order_idx').on(columns._order),
    index('solution_plans_periods_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans.id],
      name: 'solution_plans_periods_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans_periods_locales = pgTable(
  'solution_plans_periods_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('solution_plans_periods_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans_periods.id],
      name: 'solution_plans_periods_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans_addons = pgTable(
  'solution_plans_addons',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    addonId: varchar('addon_id').notNull(),
    price: numeric('price', { mode: 'number' }).notNull(),
    recommended: boolean('recommended').default(false),
    mandatory: boolean('mandatory').default(false),
  },
  (columns) => [
    index('solution_plans_addons_order_idx').on(columns._order),
    index('solution_plans_addons_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans.id],
      name: 'solution_plans_addons_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans_addons_locales = pgTable(
  'solution_plans_addons_locales',
  {
    name: varchar('name').notNull(),
    description: varchar('description'),
    note: varchar('note'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('solution_plans_addons_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans_addons.id],
      name: 'solution_plans_addons_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solution_plans = pgTable(
  'solution_plans',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug'),
    price: varchar('price').notNull(),
    currency: enum_solution_plans_currency('currency').notNull().default('ILS'),
    originalPrice: varchar('original_price'),
    priceNote: boolean('price_note').default(false),
    featured: boolean('featured').default(false),
    ctaHref: varchar('cta_href'),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('solution_plans_slug_idx').on(columns.slug),
    index('solution_plans_updated_at_idx').on(columns.updatedAt),
    index('solution_plans_created_at_idx').on(columns.createdAt),
  ],
)

export const solution_plans_locales = pgTable(
  'solution_plans_locales',
  {
    title: varchar('title').notNull(),
    pricePrefix: varchar('price_prefix'),
    disclaimer: varchar('disclaimer'),
    subtitle: varchar('subtitle'),
    promo: varchar('promo'),
    paymentNote: varchar('payment_note'),
    taxNote: varchar('tax_note'),
    taxValue: varchar('tax_value'),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('solution_plans_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solution_plans.id],
      name: 'solution_plans_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_categories = pgTable(
  'portfolio_categories',
  {
    id: serial('id').primaryKey(),
    value: varchar('value').notNull(),
    order: numeric('order', { mode: 'number' }).default(0),
    showInFilters: boolean('show_in_filters').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('portfolio_categories_value_idx').on(columns.value),
    index('portfolio_categories_updated_at_idx').on(columns.updatedAt),
    index('portfolio_categories_created_at_idx').on(columns.createdAt),
  ],
)

export const portfolio_categories_locales = pgTable(
  'portfolio_categories_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('portfolio_categories_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_categories.id],
      name: 'portfolio_categories_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_stack = pgTable(
  'portfolio_projects_stack',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    item: varchar('item').notNull(),
  },
  (columns) => [
    index('portfolio_projects_stack_order_idx').on(columns._order),
    index('portfolio_projects_stack_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects.id],
      name: 'portfolio_projects_stack_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_tags = pgTable(
  'portfolio_projects_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').notNull(),
  },
  (columns) => [
    index('portfolio_projects_tags_order_idx').on(columns._order),
    index('portfolio_projects_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects.id],
      name: 'portfolio_projects_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_body_paragraphs = pgTable(
  'portfolio_projects_body_paragraphs',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('portfolio_projects_body_paragraphs_order_idx').on(columns._order),
    index('portfolio_projects_body_paragraphs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects_body.id],
      name: 'portfolio_projects_body_paragraphs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_body_paragraphs_locales = pgTable(
  'portfolio_projects_body_paragraphs_locales',
  {
    text: varchar('text').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('portfolio_projects_body_paragraphs_locales_locale_parent_id_').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects_body_paragraphs.id],
      name: 'portfolio_projects_body_paragraphs_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_body_images = pgTable(
  'portfolio_projects_body_images',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('portfolio_projects_body_images_order_idx').on(columns._order),
    index('portfolio_projects_body_images_parent_id_idx').on(columns._parentID),
    index('portfolio_projects_body_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects_body.id],
      name: 'portfolio_projects_body_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_body = pgTable(
  'portfolio_projects_body',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('portfolio_projects_body_order_idx').on(columns._order),
    index('portfolio_projects_body_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects.id],
      name: 'portfolio_projects_body_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects_body_locales = pgTable(
  'portfolio_projects_body_locales',
  {
    heading: varchar('heading'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('portfolio_projects_body_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects_body.id],
      name: 'portfolio_projects_body_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const portfolio_projects = pgTable(
  'portfolio_projects',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    category: integer('category_id')
      .notNull()
      .references(() => portfolio_categories.id, {
        onDelete: 'set null',
      }),
    date: varchar('date'),
    client: varchar('client'),
    link: varchar('link'),
    cardImage: integer('card_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    heroMedia: integer('hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    heroMediaMobile: integer('hero_media_mobile_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('portfolio_projects_slug_idx').on(columns.slug),
    index('portfolio_projects_category_idx').on(columns.category),
    index('portfolio_projects_card_image_idx').on(columns.cardImage),
    index('portfolio_projects_hero_media_idx').on(columns.heroMedia),
    index('portfolio_projects_hero_media_mobile_idx').on(columns.heroMediaMobile),
    index('portfolio_projects_updated_at_idx').on(columns.updatedAt),
    index('portfolio_projects_created_at_idx').on(columns.createdAt),
  ],
)

export const portfolio_projects_locales = pgTable(
  'portfolio_projects_locales',
  {
    title: varchar('title').notNull(),
    categoryLabel: varchar('category_label'),
    description: varchar('description').notNull(),
    summary: varchar('summary').notNull(),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('portfolio_projects_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [portfolio_projects.id],
      name: 'portfolio_projects_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const partners = pgTable(
  'partners',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    logo: integer('logo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    url: varchar('url'),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('partners_logo_idx').on(columns.logo),
    index('partners_updated_at_idx').on(columns.updatedAt),
    index('partners_created_at_idx').on(columns.createdAt),
  ],
)

export const contact_submissions = pgTable(
  'contact_submissions',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    email: varchar('email').notNull(),
    phone: varchar('phone'),
    message: varchar('message').notNull(),
    locale: varchar('locale'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('contact_submissions_updated_at_idx').on(columns.updatedAt),
    index('contact_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    pagesID: integer('pages_id'),
    servicesID: integer('services_id'),
    'solution-plansID': integer('solution_plans_id'),
    'portfolio-categoriesID': integer('portfolio_categories_id'),
    'portfolio-projectsID': integer('portfolio_projects_id'),
    partnersID: integer('partners_id'),
    'contact-submissionsID': integer('contact_submissions_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_services_id_idx').on(columns.servicesID),
    index('payload_locked_documents_rels_solution_plans_id_idx').on(columns['solution-plansID']),
    index('payload_locked_documents_rels_portfolio_categories_id_idx').on(
      columns['portfolio-categoriesID'],
    ),
    index('payload_locked_documents_rels_portfolio_projects_id_idx').on(
      columns['portfolio-projectsID'],
    ),
    index('payload_locked_documents_rels_partners_id_idx').on(columns.partnersID),
    index('payload_locked_documents_rels_contact_submissions_id_idx').on(
      columns['contact-submissionsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'payload_locked_documents_rels_services_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['solution-plansID']],
      foreignColumns: [solution_plans.id],
      name: 'payload_locked_documents_rels_solution_plans_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['portfolio-categoriesID']],
      foreignColumns: [portfolio_categories.id],
      name: 'payload_locked_documents_rels_portfolio_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['portfolio-projectsID']],
      foreignColumns: [portfolio_projects.id],
      name: 'payload_locked_documents_rels_portfolio_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partnersID']],
      foreignColumns: [partners.id],
      name: 'payload_locked_documents_rels_partners_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['contact-submissionsID']],
      foreignColumns: [contact_submissions.id],
      name: 'payload_locked_documents_rels_contact_submissions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const header_nav_items = pgTable(
  'header_nav_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('header_nav_items_order_idx').on(columns._order),
    index('header_nav_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header.id],
      name: 'header_nav_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const header_nav_items_locales = pgTable(
  'header_nav_items_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('header_nav_items_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header_nav_items.id],
      name: 'header_nav_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const header = pgTable('header', {
  id: serial('id').primaryKey(),
  ctaHref: varchar('cta_href').default('#contact-modal'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const header_locales = pgTable(
  'header_locales',
  {
    ctaLabel: varchar('cta_label'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('header_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header.id],
      name: 'header_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const hero_words = pgTable(
  'hero_words',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('hero_words_order_idx').on(columns._order),
    index('hero_words_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hero.id],
      name: 'hero_words_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const hero_words_locales = pgTable(
  'hero_words_locales',
  {
    word: varchar('word').notNull(),
    outline: varchar('outline'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('hero_words_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hero_words.id],
      name: 'hero_words_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const hero = pgTable(
  'hero',
  {
    id: serial('id').primaryKey(),
    ctaHref: varchar('cta_href'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [index('hero_background_image_idx').on(columns.backgroundImage)],
)

export const hero_locales = pgTable(
  'hero_locales',
  {
    preHeading: varchar('pre_heading'),
    mainHeading: varchar('main_heading'),
    subtext: varchar('subtext'),
    ctaFind: varchar('cta_find'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('hero_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hero.id],
      name: 'hero_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const services_section = pgTable('services_section', {
  id: serial('id').primaryKey(),
  startCtaHref: varchar('start_cta_href').default('#contact-modal'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const services_section_locales = pgTable(
  'services_section_locales',
  {
    sectionTitle: varchar('section_title'),
    sectionSubtitle: varchar('section_subtitle'),
    startCTA: varchar('start_c_t_a'),
    priceLabel: varchar('price_label'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('services_section_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services_section.id],
      name: 'services_section_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const case_studies = pgTable(
  'case_studies',
  {
    id: serial('id').primaryKey(),
    cardCtaHref: varchar('card_cta_href').default('/portfolio'),
    viewAllHref: varchar('view_all_href').default('/portfolio'),
    bannerVideo: integer('banner_video_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    bannerVideoMobile: integer('banner_video_mobile_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('case_studies_banner_video_idx').on(columns.bannerVideo),
    index('case_studies_banner_video_mobile_idx').on(columns.bannerVideoMobile),
  ],
)

export const case_studies_locales = pgTable(
  'case_studies_locales',
  {
    preTitle: varchar('pre_title'),
    subtitle: varchar('subtitle'),
    cardTitle: varchar('card_title'),
    cardCategory: varchar('card_category'),
    cardDescription: varchar('card_description'),
    cardCTA: varchar('card_c_t_a'),
    viewAllProjects: varchar('view_all_projects'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('case_studies_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [case_studies.id],
      name: 'case_studies_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const solutions_section = pgTable('solutions_section', {
  id: serial('id').primaryKey(),
  ctaHref: varchar('cta_href'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const solutions_section_locales = pgTable(
  'solutions_section_locales',
  {
    sectionTitle: varchar('section_title'),
    sectionSubtitle: varchar('section_subtitle'),
    ctaLabel: varchar('cta_label'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('solutions_section_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [solutions_section.id],
      name: 'solutions_section_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const faq_section_items = pgTable(
  'faq_section_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('faq_section_items_order_idx').on(columns._order),
    index('faq_section_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [faq_section.id],
      name: 'faq_section_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const faq_section_items_locales = pgTable(
  'faq_section_items_locales',
  {
    question: varchar('question').notNull(),
    answer: jsonb('answer').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('faq_section_items_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [faq_section_items.id],
      name: 'faq_section_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const faq_section = pgTable('faq_section', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const faq_section_locales = pgTable(
  'faq_section_locales',
  {
    sectionTitle: varchar('section_title'),
    sectionSubtitle: varchar('section_subtitle'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('faq_section_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [faq_section.id],
      name: 'faq_section_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footer_company_links = pgTable(
  'footer_company_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('footer_company_links_order_idx').on(columns._order),
    index('footer_company_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_company_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footer_company_links_locales = pgTable(
  'footer_company_links_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('footer_company_links_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer_company_links.id],
      name: 'footer_company_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footer_legal_links = pgTable(
  'footer_legal_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    key: varchar('key'),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('footer_legal_links_order_idx').on(columns._order),
    index('footer_legal_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_legal_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footer_legal_links_locales = pgTable(
  'footer_legal_links_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('footer_legal_links_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer_legal_links.id],
      name: 'footer_legal_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footer = pgTable('footer', {
  id: serial('id').primaryKey(),
  ctaHref: varchar('cta_href').default('#contact-modal'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const footer_locales = pgTable(
  'footer_locales',
  {
    ctaHeadingLine1: varchar('cta_heading_line1'),
    ctaHeadingLine2: varchar('cta_heading_line2'),
    ctaButton: varchar('cta_button'),
    companyTitle: varchar('company_title'),
    contactTitle: varchar('contact_title'),
    emailLabel: varchar('email_label'),
    phoneLabel: varchar('phone_label'),
    locationLabel: varchar('location_label'),
    locationValue: varchar('location_value'),
    copyright: varchar('copyright'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('footer_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_settings = pgTable(
  'site_settings',
  {
    id: serial('id').primaryKey(),
    email: varchar('email'),
    phone: varchar('phone'),
    phoneDisplay: varchar('phone_display'),
    facebook: varchar('facebook'),
    tiktok: varchar('tiktok'),
    seoTitle: varchar('seo_title'),
    ogImage: integer('og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    contactsHeroMedia: integer('contacts_hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    portfolioHeroMedia: integer('portfolio_hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    legalHeroMedia: integer('legal_hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    orderHeroMedia: integer('order_hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('site_settings_og_image_idx').on(columns.ogImage),
    index('site_settings_contacts_hero_media_idx').on(columns.contactsHeroMedia),
    index('site_settings_portfolio_hero_media_idx').on(columns.portfolioHeroMedia),
    index('site_settings_legal_hero_media_idx').on(columns.legalHeroMedia),
    index('site_settings_order_hero_media_idx').on(columns.orderHeroMedia),
  ],
)

export const site_settings_locales = pgTable(
  'site_settings_locales',
  {
    cookieMessage: varchar('cookie_message'),
    cookieAccept: varchar('cookie_accept'),
    cookieDecline: varchar('cookie_decline'),
    seoDescription: varchar('seo_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('site_settings_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_privacy_sections = pgTable(
  'legal_privacy_sections',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('legal_privacy_sections_order_idx').on(columns._order),
    index('legal_privacy_sections_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_privacy.id],
      name: 'legal_privacy_sections_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_privacy_sections_locales = pgTable(
  'legal_privacy_sections_locales',
  {
    heading: varchar('heading').notNull(),
    paragraphs: varchar('paragraphs'),
    bullets: varchar('bullets'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('legal_privacy_sections_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_privacy_sections.id],
      name: 'legal_privacy_sections_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_privacy = pgTable('legal_privacy', {
  id: serial('id').primaryKey(),
  statementDate: varchar('statement_date'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const legal_privacy_locales = pgTable(
  'legal_privacy_locales',
  {
    title: varchar('title').notNull(),
    metaDescription: varchar('meta_description'),
    intro: varchar('intro'),
    closing: varchar('closing'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('legal_privacy_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_privacy.id],
      name: 'legal_privacy_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_terms_sections = pgTable(
  'legal_terms_sections',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('legal_terms_sections_order_idx').on(columns._order),
    index('legal_terms_sections_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_terms.id],
      name: 'legal_terms_sections_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_terms_sections_locales = pgTable(
  'legal_terms_sections_locales',
  {
    heading: varchar('heading').notNull(),
    paragraphs: varchar('paragraphs'),
    bullets: varchar('bullets'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('legal_terms_sections_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_terms_sections.id],
      name: 'legal_terms_sections_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_terms = pgTable('legal_terms', {
  id: serial('id').primaryKey(),
  statementDate: varchar('statement_date'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const legal_terms_locales = pgTable(
  'legal_terms_locales',
  {
    title: varchar('title').notNull(),
    metaDescription: varchar('meta_description'),
    intro: varchar('intro'),
    closing: varchar('closing'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('legal_terms_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_terms.id],
      name: 'legal_terms_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_accessibility_sections = pgTable(
  'legal_accessibility_sections',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('legal_accessibility_sections_order_idx').on(columns._order),
    index('legal_accessibility_sections_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_accessibility.id],
      name: 'legal_accessibility_sections_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_accessibility_sections_locales = pgTable(
  'legal_accessibility_sections_locales',
  {
    heading: varchar('heading').notNull(),
    paragraphs: varchar('paragraphs'),
    bullets: varchar('bullets'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('legal_accessibility_sections_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_accessibility_sections.id],
      name: 'legal_accessibility_sections_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_accessibility = pgTable('legal_accessibility', {
  id: serial('id').primaryKey(),
  statementDate: varchar('statement_date'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const legal_accessibility_locales = pgTable(
  'legal_accessibility_locales',
  {
    title: varchar('title').notNull(),
    metaDescription: varchar('meta_description'),
    intro: varchar('intro'),
    closing: varchar('closing'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('legal_accessibility_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_accessibility.id],
      name: 'legal_accessibility_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_pages_blocks_hero_block_locales = relations(
  pages_blocks_hero_block_locales,
  ({ one }) => ({
    _parentID: one(pages_blocks_hero_block, {
      fields: [pages_blocks_hero_block_locales._parentID],
      references: [pages_blocks_hero_block.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_pages_blocks_hero_block = relations(
  pages_blocks_hero_block,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_hero_block._parentID],
      references: [pages.id],
      relationName: '_blocks_heroBlock',
    }),
    _locales: many(pages_blocks_hero_block_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_pages_blocks_word_stack_block_words = relations(
  pages_blocks_word_stack_block_words,
  ({ one }) => ({
    _parentID: one(pages_blocks_word_stack_block, {
      fields: [pages_blocks_word_stack_block_words._parentID],
      references: [pages_blocks_word_stack_block.id],
      relationName: 'words',
    }),
  }),
)
export const relations_pages_blocks_word_stack_block = relations(
  pages_blocks_word_stack_block,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_word_stack_block._parentID],
      references: [pages.id],
      relationName: '_blocks_wordStackBlock',
    }),
    words: many(pages_blocks_word_stack_block_words, {
      relationName: 'words',
    }),
  }),
)
export const relations_pages = relations(pages, ({ many }) => ({
  _blocks_heroBlock: many(pages_blocks_hero_block, {
    relationName: '_blocks_heroBlock',
  }),
  _blocks_wordStackBlock: many(pages_blocks_word_stack_block, {
    relationName: '_blocks_wordStackBlock',
  }),
}))
export const relations_services_features_locales = relations(
  services_features_locales,
  ({ one }) => ({
    _parentID: one(services_features, {
      fields: [services_features_locales._parentID],
      references: [services_features.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_services_features = relations(services_features, ({ one, many }) => ({
  _parentID: one(services, {
    fields: [services_features._parentID],
    references: [services.id],
    relationName: 'features',
  }),
  _locales: many(services_features_locales, {
    relationName: '_locales',
  }),
}))
export const relations_services_offerings_locales = relations(
  services_offerings_locales,
  ({ one }) => ({
    _parentID: one(services_offerings, {
      fields: [services_offerings_locales._parentID],
      references: [services_offerings.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_services_offerings = relations(services_offerings, ({ one, many }) => ({
  _parentID: one(services, {
    fields: [services_offerings._parentID],
    references: [services.id],
    relationName: 'offerings',
  }),
  _locales: many(services_offerings_locales, {
    relationName: '_locales',
  }),
}))
export const relations_services_locales = relations(services_locales, ({ one }) => ({
  _parentID: one(services, {
    fields: [services_locales._parentID],
    references: [services.id],
    relationName: '_locales',
  }),
}))
export const relations_services = relations(services, ({ one, many }) => ({
  image: one(media, {
    fields: [services.image],
    references: [media.id],
    relationName: 'image',
  }),
  heroMedia: one(media, {
    fields: [services.heroMedia],
    references: [media.id],
    relationName: 'heroMedia',
  }),
  features: many(services_features, {
    relationName: 'features',
  }),
  offerings: many(services_offerings, {
    relationName: 'offerings',
  }),
  _locales: many(services_locales, {
    relationName: '_locales',
  }),
}))
export const relations_solution_plans_features_locales = relations(
  solution_plans_features_locales,
  ({ one }) => ({
    _parentID: one(solution_plans_features, {
      fields: [solution_plans_features_locales._parentID],
      references: [solution_plans_features.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_solution_plans_features = relations(
  solution_plans_features,
  ({ one, many }) => ({
    _parentID: one(solution_plans, {
      fields: [solution_plans_features._parentID],
      references: [solution_plans.id],
      relationName: 'features',
    }),
    _locales: many(solution_plans_features_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_solution_plans_periods_locales = relations(
  solution_plans_periods_locales,
  ({ one }) => ({
    _parentID: one(solution_plans_periods, {
      fields: [solution_plans_periods_locales._parentID],
      references: [solution_plans_periods.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_solution_plans_periods = relations(
  solution_plans_periods,
  ({ one, many }) => ({
    _parentID: one(solution_plans, {
      fields: [solution_plans_periods._parentID],
      references: [solution_plans.id],
      relationName: 'periods',
    }),
    _locales: many(solution_plans_periods_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_solution_plans_addons_locales = relations(
  solution_plans_addons_locales,
  ({ one }) => ({
    _parentID: one(solution_plans_addons, {
      fields: [solution_plans_addons_locales._parentID],
      references: [solution_plans_addons.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_solution_plans_addons = relations(
  solution_plans_addons,
  ({ one, many }) => ({
    _parentID: one(solution_plans, {
      fields: [solution_plans_addons._parentID],
      references: [solution_plans.id],
      relationName: 'addons',
    }),
    _locales: many(solution_plans_addons_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_solution_plans_locales = relations(solution_plans_locales, ({ one }) => ({
  _parentID: one(solution_plans, {
    fields: [solution_plans_locales._parentID],
    references: [solution_plans.id],
    relationName: '_locales',
  }),
}))
export const relations_solution_plans = relations(solution_plans, ({ many }) => ({
  features: many(solution_plans_features, {
    relationName: 'features',
  }),
  periods: many(solution_plans_periods, {
    relationName: 'periods',
  }),
  addons: many(solution_plans_addons, {
    relationName: 'addons',
  }),
  _locales: many(solution_plans_locales, {
    relationName: '_locales',
  }),
}))
export const relations_portfolio_categories_locales = relations(
  portfolio_categories_locales,
  ({ one }) => ({
    _parentID: one(portfolio_categories, {
      fields: [portfolio_categories_locales._parentID],
      references: [portfolio_categories.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_portfolio_categories = relations(portfolio_categories, ({ many }) => ({
  _locales: many(portfolio_categories_locales, {
    relationName: '_locales',
  }),
}))
export const relations_portfolio_projects_stack = relations(
  portfolio_projects_stack,
  ({ one }) => ({
    _parentID: one(portfolio_projects, {
      fields: [portfolio_projects_stack._parentID],
      references: [portfolio_projects.id],
      relationName: 'stack',
    }),
  }),
)
export const relations_portfolio_projects_tags = relations(portfolio_projects_tags, ({ one }) => ({
  _parentID: one(portfolio_projects, {
    fields: [portfolio_projects_tags._parentID],
    references: [portfolio_projects.id],
    relationName: 'tags',
  }),
}))
export const relations_portfolio_projects_body_paragraphs_locales = relations(
  portfolio_projects_body_paragraphs_locales,
  ({ one }) => ({
    _parentID: one(portfolio_projects_body_paragraphs, {
      fields: [portfolio_projects_body_paragraphs_locales._parentID],
      references: [portfolio_projects_body_paragraphs.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_portfolio_projects_body_paragraphs = relations(
  portfolio_projects_body_paragraphs,
  ({ one, many }) => ({
    _parentID: one(portfolio_projects_body, {
      fields: [portfolio_projects_body_paragraphs._parentID],
      references: [portfolio_projects_body.id],
      relationName: 'paragraphs',
    }),
    _locales: many(portfolio_projects_body_paragraphs_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_portfolio_projects_body_images = relations(
  portfolio_projects_body_images,
  ({ one }) => ({
    _parentID: one(portfolio_projects_body, {
      fields: [portfolio_projects_body_images._parentID],
      references: [portfolio_projects_body.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [portfolio_projects_body_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_portfolio_projects_body_locales = relations(
  portfolio_projects_body_locales,
  ({ one }) => ({
    _parentID: one(portfolio_projects_body, {
      fields: [portfolio_projects_body_locales._parentID],
      references: [portfolio_projects_body.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_portfolio_projects_body = relations(
  portfolio_projects_body,
  ({ one, many }) => ({
    _parentID: one(portfolio_projects, {
      fields: [portfolio_projects_body._parentID],
      references: [portfolio_projects.id],
      relationName: 'body',
    }),
    _locales: many(portfolio_projects_body_locales, {
      relationName: '_locales',
    }),
    paragraphs: many(portfolio_projects_body_paragraphs, {
      relationName: 'paragraphs',
    }),
    images: many(portfolio_projects_body_images, {
      relationName: 'images',
    }),
  }),
)
export const relations_portfolio_projects_locales = relations(
  portfolio_projects_locales,
  ({ one }) => ({
    _parentID: one(portfolio_projects, {
      fields: [portfolio_projects_locales._parentID],
      references: [portfolio_projects.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_portfolio_projects = relations(portfolio_projects, ({ one, many }) => ({
  category: one(portfolio_categories, {
    fields: [portfolio_projects.category],
    references: [portfolio_categories.id],
    relationName: 'category',
  }),
  stack: many(portfolio_projects_stack, {
    relationName: 'stack',
  }),
  tags: many(portfolio_projects_tags, {
    relationName: 'tags',
  }),
  cardImage: one(media, {
    fields: [portfolio_projects.cardImage],
    references: [media.id],
    relationName: 'cardImage',
  }),
  heroMedia: one(media, {
    fields: [portfolio_projects.heroMedia],
    references: [media.id],
    relationName: 'heroMedia',
  }),
  heroMediaMobile: one(media, {
    fields: [portfolio_projects.heroMediaMobile],
    references: [media.id],
    relationName: 'heroMediaMobile',
  }),
  body: many(portfolio_projects_body, {
    relationName: 'body',
  }),
  _locales: many(portfolio_projects_locales, {
    relationName: '_locales',
  }),
}))
export const relations_partners = relations(partners, ({ one }) => ({
  logo: one(media, {
    fields: [partners.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_contact_submissions = relations(contact_submissions, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: 'services',
    }),
    'solution-plansID': one(solution_plans, {
      fields: [payload_locked_documents_rels['solution-plansID']],
      references: [solution_plans.id],
      relationName: 'solution-plans',
    }),
    'portfolio-categoriesID': one(portfolio_categories, {
      fields: [payload_locked_documents_rels['portfolio-categoriesID']],
      references: [portfolio_categories.id],
      relationName: 'portfolio-categories',
    }),
    'portfolio-projectsID': one(portfolio_projects, {
      fields: [payload_locked_documents_rels['portfolio-projectsID']],
      references: [portfolio_projects.id],
      relationName: 'portfolio-projects',
    }),
    partnersID: one(partners, {
      fields: [payload_locked_documents_rels.partnersID],
      references: [partners.id],
      relationName: 'partners',
    }),
    'contact-submissionsID': one(contact_submissions, {
      fields: [payload_locked_documents_rels['contact-submissionsID']],
      references: [contact_submissions.id],
      relationName: 'contact-submissions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_header_nav_items_locales = relations(
  header_nav_items_locales,
  ({ one }) => ({
    _parentID: one(header_nav_items, {
      fields: [header_nav_items_locales._parentID],
      references: [header_nav_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_header_nav_items = relations(header_nav_items, ({ one, many }) => ({
  _parentID: one(header, {
    fields: [header_nav_items._parentID],
    references: [header.id],
    relationName: 'navItems',
  }),
  _locales: many(header_nav_items_locales, {
    relationName: '_locales',
  }),
}))
export const relations_header_locales = relations(header_locales, ({ one }) => ({
  _parentID: one(header, {
    fields: [header_locales._parentID],
    references: [header.id],
    relationName: '_locales',
  }),
}))
export const relations_header = relations(header, ({ many }) => ({
  navItems: many(header_nav_items, {
    relationName: 'navItems',
  }),
  _locales: many(header_locales, {
    relationName: '_locales',
  }),
}))
export const relations_hero_words_locales = relations(hero_words_locales, ({ one }) => ({
  _parentID: one(hero_words, {
    fields: [hero_words_locales._parentID],
    references: [hero_words.id],
    relationName: '_locales',
  }),
}))
export const relations_hero_words = relations(hero_words, ({ one, many }) => ({
  _parentID: one(hero, {
    fields: [hero_words._parentID],
    references: [hero.id],
    relationName: 'words',
  }),
  _locales: many(hero_words_locales, {
    relationName: '_locales',
  }),
}))
export const relations_hero_locales = relations(hero_locales, ({ one }) => ({
  _parentID: one(hero, {
    fields: [hero_locales._parentID],
    references: [hero.id],
    relationName: '_locales',
  }),
}))
export const relations_hero = relations(hero, ({ one, many }) => ({
  backgroundImage: one(media, {
    fields: [hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
  words: many(hero_words, {
    relationName: 'words',
  }),
  _locales: many(hero_locales, {
    relationName: '_locales',
  }),
}))
export const relations_services_section_locales = relations(
  services_section_locales,
  ({ one }) => ({
    _parentID: one(services_section, {
      fields: [services_section_locales._parentID],
      references: [services_section.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_services_section = relations(services_section, ({ many }) => ({
  _locales: many(services_section_locales, {
    relationName: '_locales',
  }),
}))
export const relations_case_studies_locales = relations(case_studies_locales, ({ one }) => ({
  _parentID: one(case_studies, {
    fields: [case_studies_locales._parentID],
    references: [case_studies.id],
    relationName: '_locales',
  }),
}))
export const relations_case_studies = relations(case_studies, ({ one, many }) => ({
  bannerVideo: one(media, {
    fields: [case_studies.bannerVideo],
    references: [media.id],
    relationName: 'bannerVideo',
  }),
  bannerVideoMobile: one(media, {
    fields: [case_studies.bannerVideoMobile],
    references: [media.id],
    relationName: 'bannerVideoMobile',
  }),
  _locales: many(case_studies_locales, {
    relationName: '_locales',
  }),
}))
export const relations_solutions_section_locales = relations(
  solutions_section_locales,
  ({ one }) => ({
    _parentID: one(solutions_section, {
      fields: [solutions_section_locales._parentID],
      references: [solutions_section.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_solutions_section = relations(solutions_section, ({ many }) => ({
  _locales: many(solutions_section_locales, {
    relationName: '_locales',
  }),
}))
export const relations_faq_section_items_locales = relations(
  faq_section_items_locales,
  ({ one }) => ({
    _parentID: one(faq_section_items, {
      fields: [faq_section_items_locales._parentID],
      references: [faq_section_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_faq_section_items = relations(faq_section_items, ({ one, many }) => ({
  _parentID: one(faq_section, {
    fields: [faq_section_items._parentID],
    references: [faq_section.id],
    relationName: 'items',
  }),
  _locales: many(faq_section_items_locales, {
    relationName: '_locales',
  }),
}))
export const relations_faq_section_locales = relations(faq_section_locales, ({ one }) => ({
  _parentID: one(faq_section, {
    fields: [faq_section_locales._parentID],
    references: [faq_section.id],
    relationName: '_locales',
  }),
}))
export const relations_faq_section = relations(faq_section, ({ many }) => ({
  items: many(faq_section_items, {
    relationName: 'items',
  }),
  _locales: many(faq_section_locales, {
    relationName: '_locales',
  }),
}))
export const relations_footer_company_links_locales = relations(
  footer_company_links_locales,
  ({ one }) => ({
    _parentID: one(footer_company_links, {
      fields: [footer_company_links_locales._parentID],
      references: [footer_company_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_footer_company_links = relations(footer_company_links, ({ one, many }) => ({
  _parentID: one(footer, {
    fields: [footer_company_links._parentID],
    references: [footer.id],
    relationName: 'companyLinks',
  }),
  _locales: many(footer_company_links_locales, {
    relationName: '_locales',
  }),
}))
export const relations_footer_legal_links_locales = relations(
  footer_legal_links_locales,
  ({ one }) => ({
    _parentID: one(footer_legal_links, {
      fields: [footer_legal_links_locales._parentID],
      references: [footer_legal_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_footer_legal_links = relations(footer_legal_links, ({ one, many }) => ({
  _parentID: one(footer, {
    fields: [footer_legal_links._parentID],
    references: [footer.id],
    relationName: 'legalLinks',
  }),
  _locales: many(footer_legal_links_locales, {
    relationName: '_locales',
  }),
}))
export const relations_footer_locales = relations(footer_locales, ({ one }) => ({
  _parentID: one(footer, {
    fields: [footer_locales._parentID],
    references: [footer.id],
    relationName: '_locales',
  }),
}))
export const relations_footer = relations(footer, ({ many }) => ({
  companyLinks: many(footer_company_links, {
    relationName: 'companyLinks',
  }),
  legalLinks: many(footer_legal_links, {
    relationName: 'legalLinks',
  }),
  _locales: many(footer_locales, {
    relationName: '_locales',
  }),
}))
export const relations_site_settings_locales = relations(site_settings_locales, ({ one }) => ({
  _parentID: one(site_settings, {
    fields: [site_settings_locales._parentID],
    references: [site_settings.id],
    relationName: '_locales',
  }),
}))
export const relations_site_settings = relations(site_settings, ({ one, many }) => ({
  ogImage: one(media, {
    fields: [site_settings.ogImage],
    references: [media.id],
    relationName: 'ogImage',
  }),
  contactsHeroMedia: one(media, {
    fields: [site_settings.contactsHeroMedia],
    references: [media.id],
    relationName: 'contactsHeroMedia',
  }),
  portfolioHeroMedia: one(media, {
    fields: [site_settings.portfolioHeroMedia],
    references: [media.id],
    relationName: 'portfolioHeroMedia',
  }),
  legalHeroMedia: one(media, {
    fields: [site_settings.legalHeroMedia],
    references: [media.id],
    relationName: 'legalHeroMedia',
  }),
  orderHeroMedia: one(media, {
    fields: [site_settings.orderHeroMedia],
    references: [media.id],
    relationName: 'orderHeroMedia',
  }),
  _locales: many(site_settings_locales, {
    relationName: '_locales',
  }),
}))
export const relations_legal_privacy_sections_locales = relations(
  legal_privacy_sections_locales,
  ({ one }) => ({
    _parentID: one(legal_privacy_sections, {
      fields: [legal_privacy_sections_locales._parentID],
      references: [legal_privacy_sections.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_legal_privacy_sections = relations(
  legal_privacy_sections,
  ({ one, many }) => ({
    _parentID: one(legal_privacy, {
      fields: [legal_privacy_sections._parentID],
      references: [legal_privacy.id],
      relationName: 'sections',
    }),
    _locales: many(legal_privacy_sections_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_legal_privacy_locales = relations(legal_privacy_locales, ({ one }) => ({
  _parentID: one(legal_privacy, {
    fields: [legal_privacy_locales._parentID],
    references: [legal_privacy.id],
    relationName: '_locales',
  }),
}))
export const relations_legal_privacy = relations(legal_privacy, ({ many }) => ({
  sections: many(legal_privacy_sections, {
    relationName: 'sections',
  }),
  _locales: many(legal_privacy_locales, {
    relationName: '_locales',
  }),
}))
export const relations_legal_terms_sections_locales = relations(
  legal_terms_sections_locales,
  ({ one }) => ({
    _parentID: one(legal_terms_sections, {
      fields: [legal_terms_sections_locales._parentID],
      references: [legal_terms_sections.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_legal_terms_sections = relations(legal_terms_sections, ({ one, many }) => ({
  _parentID: one(legal_terms, {
    fields: [legal_terms_sections._parentID],
    references: [legal_terms.id],
    relationName: 'sections',
  }),
  _locales: many(legal_terms_sections_locales, {
    relationName: '_locales',
  }),
}))
export const relations_legal_terms_locales = relations(legal_terms_locales, ({ one }) => ({
  _parentID: one(legal_terms, {
    fields: [legal_terms_locales._parentID],
    references: [legal_terms.id],
    relationName: '_locales',
  }),
}))
export const relations_legal_terms = relations(legal_terms, ({ many }) => ({
  sections: many(legal_terms_sections, {
    relationName: 'sections',
  }),
  _locales: many(legal_terms_locales, {
    relationName: '_locales',
  }),
}))
export const relations_legal_accessibility_sections_locales = relations(
  legal_accessibility_sections_locales,
  ({ one }) => ({
    _parentID: one(legal_accessibility_sections, {
      fields: [legal_accessibility_sections_locales._parentID],
      references: [legal_accessibility_sections.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_legal_accessibility_sections = relations(
  legal_accessibility_sections,
  ({ one, many }) => ({
    _parentID: one(legal_accessibility, {
      fields: [legal_accessibility_sections._parentID],
      references: [legal_accessibility.id],
      relationName: 'sections',
    }),
    _locales: many(legal_accessibility_sections_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_legal_accessibility_locales = relations(
  legal_accessibility_locales,
  ({ one }) => ({
    _parentID: one(legal_accessibility, {
      fields: [legal_accessibility_locales._parentID],
      references: [legal_accessibility.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_legal_accessibility = relations(legal_accessibility, ({ many }) => ({
  sections: many(legal_accessibility_sections, {
    relationName: 'sections',
  }),
  _locales: many(legal_accessibility_locales, {
    relationName: '_locales',
  }),
}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_services_currency: typeof enum_services_currency
  enum_solution_plans_currency: typeof enum_solution_plans_currency
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  pages_blocks_hero_block: typeof pages_blocks_hero_block
  pages_blocks_hero_block_locales: typeof pages_blocks_hero_block_locales
  pages_blocks_word_stack_block_words: typeof pages_blocks_word_stack_block_words
  pages_blocks_word_stack_block: typeof pages_blocks_word_stack_block
  pages: typeof pages
  services_features: typeof services_features
  services_features_locales: typeof services_features_locales
  services_offerings: typeof services_offerings
  services_offerings_locales: typeof services_offerings_locales
  services: typeof services
  services_locales: typeof services_locales
  solution_plans_features: typeof solution_plans_features
  solution_plans_features_locales: typeof solution_plans_features_locales
  solution_plans_periods: typeof solution_plans_periods
  solution_plans_periods_locales: typeof solution_plans_periods_locales
  solution_plans_addons: typeof solution_plans_addons
  solution_plans_addons_locales: typeof solution_plans_addons_locales
  solution_plans: typeof solution_plans
  solution_plans_locales: typeof solution_plans_locales
  portfolio_categories: typeof portfolio_categories
  portfolio_categories_locales: typeof portfolio_categories_locales
  portfolio_projects_stack: typeof portfolio_projects_stack
  portfolio_projects_tags: typeof portfolio_projects_tags
  portfolio_projects_body_paragraphs: typeof portfolio_projects_body_paragraphs
  portfolio_projects_body_paragraphs_locales: typeof portfolio_projects_body_paragraphs_locales
  portfolio_projects_body_images: typeof portfolio_projects_body_images
  portfolio_projects_body: typeof portfolio_projects_body
  portfolio_projects_body_locales: typeof portfolio_projects_body_locales
  portfolio_projects: typeof portfolio_projects
  portfolio_projects_locales: typeof portfolio_projects_locales
  partners: typeof partners
  contact_submissions: typeof contact_submissions
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  header_nav_items: typeof header_nav_items
  header_nav_items_locales: typeof header_nav_items_locales
  header: typeof header
  header_locales: typeof header_locales
  hero_words: typeof hero_words
  hero_words_locales: typeof hero_words_locales
  hero: typeof hero
  hero_locales: typeof hero_locales
  services_section: typeof services_section
  services_section_locales: typeof services_section_locales
  case_studies: typeof case_studies
  case_studies_locales: typeof case_studies_locales
  solutions_section: typeof solutions_section
  solutions_section_locales: typeof solutions_section_locales
  faq_section_items: typeof faq_section_items
  faq_section_items_locales: typeof faq_section_items_locales
  faq_section: typeof faq_section
  faq_section_locales: typeof faq_section_locales
  footer_company_links: typeof footer_company_links
  footer_company_links_locales: typeof footer_company_links_locales
  footer_legal_links: typeof footer_legal_links
  footer_legal_links_locales: typeof footer_legal_links_locales
  footer: typeof footer
  footer_locales: typeof footer_locales
  site_settings: typeof site_settings
  site_settings_locales: typeof site_settings_locales
  legal_privacy_sections: typeof legal_privacy_sections
  legal_privacy_sections_locales: typeof legal_privacy_sections_locales
  legal_privacy: typeof legal_privacy
  legal_privacy_locales: typeof legal_privacy_locales
  legal_terms_sections: typeof legal_terms_sections
  legal_terms_sections_locales: typeof legal_terms_sections_locales
  legal_terms: typeof legal_terms
  legal_terms_locales: typeof legal_terms_locales
  legal_accessibility_sections: typeof legal_accessibility_sections
  legal_accessibility_sections_locales: typeof legal_accessibility_sections_locales
  legal_accessibility: typeof legal_accessibility
  legal_accessibility_locales: typeof legal_accessibility_locales
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_pages_blocks_hero_block_locales: typeof relations_pages_blocks_hero_block_locales
  relations_pages_blocks_hero_block: typeof relations_pages_blocks_hero_block
  relations_pages_blocks_word_stack_block_words: typeof relations_pages_blocks_word_stack_block_words
  relations_pages_blocks_word_stack_block: typeof relations_pages_blocks_word_stack_block
  relations_pages: typeof relations_pages
  relations_services_features_locales: typeof relations_services_features_locales
  relations_services_features: typeof relations_services_features
  relations_services_offerings_locales: typeof relations_services_offerings_locales
  relations_services_offerings: typeof relations_services_offerings
  relations_services_locales: typeof relations_services_locales
  relations_services: typeof relations_services
  relations_solution_plans_features_locales: typeof relations_solution_plans_features_locales
  relations_solution_plans_features: typeof relations_solution_plans_features
  relations_solution_plans_periods_locales: typeof relations_solution_plans_periods_locales
  relations_solution_plans_periods: typeof relations_solution_plans_periods
  relations_solution_plans_addons_locales: typeof relations_solution_plans_addons_locales
  relations_solution_plans_addons: typeof relations_solution_plans_addons
  relations_solution_plans_locales: typeof relations_solution_plans_locales
  relations_solution_plans: typeof relations_solution_plans
  relations_portfolio_categories_locales: typeof relations_portfolio_categories_locales
  relations_portfolio_categories: typeof relations_portfolio_categories
  relations_portfolio_projects_stack: typeof relations_portfolio_projects_stack
  relations_portfolio_projects_tags: typeof relations_portfolio_projects_tags
  relations_portfolio_projects_body_paragraphs_locales: typeof relations_portfolio_projects_body_paragraphs_locales
  relations_portfolio_projects_body_paragraphs: typeof relations_portfolio_projects_body_paragraphs
  relations_portfolio_projects_body_images: typeof relations_portfolio_projects_body_images
  relations_portfolio_projects_body_locales: typeof relations_portfolio_projects_body_locales
  relations_portfolio_projects_body: typeof relations_portfolio_projects_body
  relations_portfolio_projects_locales: typeof relations_portfolio_projects_locales
  relations_portfolio_projects: typeof relations_portfolio_projects
  relations_partners: typeof relations_partners
  relations_contact_submissions: typeof relations_contact_submissions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_header_nav_items_locales: typeof relations_header_nav_items_locales
  relations_header_nav_items: typeof relations_header_nav_items
  relations_header_locales: typeof relations_header_locales
  relations_header: typeof relations_header
  relations_hero_words_locales: typeof relations_hero_words_locales
  relations_hero_words: typeof relations_hero_words
  relations_hero_locales: typeof relations_hero_locales
  relations_hero: typeof relations_hero
  relations_services_section_locales: typeof relations_services_section_locales
  relations_services_section: typeof relations_services_section
  relations_case_studies_locales: typeof relations_case_studies_locales
  relations_case_studies: typeof relations_case_studies
  relations_solutions_section_locales: typeof relations_solutions_section_locales
  relations_solutions_section: typeof relations_solutions_section
  relations_faq_section_items_locales: typeof relations_faq_section_items_locales
  relations_faq_section_items: typeof relations_faq_section_items
  relations_faq_section_locales: typeof relations_faq_section_locales
  relations_faq_section: typeof relations_faq_section
  relations_footer_company_links_locales: typeof relations_footer_company_links_locales
  relations_footer_company_links: typeof relations_footer_company_links
  relations_footer_legal_links_locales: typeof relations_footer_legal_links_locales
  relations_footer_legal_links: typeof relations_footer_legal_links
  relations_footer_locales: typeof relations_footer_locales
  relations_footer: typeof relations_footer
  relations_site_settings_locales: typeof relations_site_settings_locales
  relations_site_settings: typeof relations_site_settings
  relations_legal_privacy_sections_locales: typeof relations_legal_privacy_sections_locales
  relations_legal_privacy_sections: typeof relations_legal_privacy_sections
  relations_legal_privacy_locales: typeof relations_legal_privacy_locales
  relations_legal_privacy: typeof relations_legal_privacy
  relations_legal_terms_sections_locales: typeof relations_legal_terms_sections_locales
  relations_legal_terms_sections: typeof relations_legal_terms_sections
  relations_legal_terms_locales: typeof relations_legal_terms_locales
  relations_legal_terms: typeof relations_legal_terms
  relations_legal_accessibility_sections_locales: typeof relations_legal_accessibility_sections_locales
  relations_legal_accessibility_sections: typeof relations_legal_accessibility_sections
  relations_legal_accessibility_locales: typeof relations_legal_accessibility_locales
  relations_legal_accessibility: typeof relations_legal_accessibility
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
