/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    'solution-plans': SolutionPlan;
    'portfolio-categories': PortfolioCategory;
    'portfolio-projects': PortfolioProject;
    partners: Partner;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'solution-plans': SolutionPlansSelect<false> | SolutionPlansSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    'portfolio-projects': PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'he') | ('en' | 'ru' | 'he')[];
  globals: {
    header: Header;
    hero: Hero;
    'services-section': ServicesSection;
    'case-studies': CaseStudy;
    'solutions-section': SolutionsSection;
    'faq-section': FaqSection;
    footer: Footer;
    'site-settings': SiteSetting;
    'legal-privacy': LegalPrivacy;
    'legal-terms': LegalTerm;
    'legal-accessibility': LegalAccessibility;
    'audit-page': AuditPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'services-section': ServicesSectionSelect<false> | ServicesSectionSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'solutions-section': SolutionsSectionSelect<false> | SolutionsSectionSelect<true>;
    'faq-section': FaqSectionSelect<false> | FaqSectionSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'legal-privacy': LegalPrivacySelect<false> | LegalPrivacySelect<true>;
    'legal-terms': LegalTermsSelect<false> | LegalTermsSelect<true>;
    'legal-accessibility': LegalAccessibilitySelect<false> | LegalAccessibilitySelect<true>;
    'audit-page': AuditPageSelect<false> | AuditPageSelect<true>;
  };
  locale: 'en' | 'ru' | 'he';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            title?: string | null;
            ctaText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
        | {
            words?:
              | {
                  word: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'wordStackBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL for the service page, e.g. "design-branding" → /services/design-branding. Also used by the home card “more” link.
   */
  slug?: string | null;
  /**
   * Display number, e.g. "01"
   */
  number?: string | null;
  /**
   * Card image/video. Recommended: 1600×1000 px (16:10), minimum 1200 px wide. Images are stored in original quality without upload compression. MP4/WebM videos autoplay muted.
   */
  image?: (number | null) | Media;
  /**
   * Wide header image/video for /services/[slug]. Recommended: 1920×150 px (matches contacts/portfolio header strip), minimum 1600×150 px. Images are stored in original quality without upload compression. Falls back to the card media.
   */
  heroMedia?: (number | null) | Media;
  /**
   * Currency used for all packages and prices on this service page
   */
  currency: 'USD' | 'ILS' | 'EUR';
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Short intro on the service detail page (rich text)
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Detailed description on the service page (rich text)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  offerings?:
    | {
        name: string;
        description?: string | null;
        /**
         * e.g. "2 500"
         */
        price: string;
        /**
         * e.g. "from" / "от"
         */
        pricePrefix?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If empty, the page title and intro text are used for search engines and social previews.
   */
  seo?: {
    /**
     * Meta title. Example: "Design & Branding | Erythro.ai"
     */
    title?: string | null;
    /**
     * Meta description (recommended up to ~160 characters).
     */
    description?: string | null;
  };
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solution plans (homepage Solutions + /order) and AI Audit plans (/order/audit-*). Use the "Kind" field to separate them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-plans".
 */
export interface SolutionPlan {
  id: number;
  title: string;
  /**
   * Solution = homepage Solutions section + /order. AI Audit = /order/audit-* only (hidden from homepage Solutions).
   */
  kind: 'solution' | 'audit';
  /**
   * Stable id / order URL, e.g. "business-automation" → /order/business-automation
   */
  slug?: string | null;
  /**
   * Main price value, e.g. "14 999" or "0"
   */
  price: string;
  /**
   * Currency shown next to the price on the site and order page
   */
  currency: 'ILS' | 'USD' | 'EUR';
  /**
   * Optional prefix, e.g. "from" / "от"
   */
  pricePrefix?: string | null;
  /**
   * Optional old/struck-through price
   */
  originalPrice?: string | null;
  /**
   * Show installment note marker (*)
   */
  priceNote?: boolean | null;
  /**
   * Highlight this plan as recommended
   */
  featured?: boolean | null;
  /**
   * Label + Value show on homepage cards and on the order package accordion. For “Подписка / Subscription” use Label + Value only (homepage); put price details and Full on the Monthly subscription Add-on.
   */
  features?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  disclaimer?: string | null;
  /**
   * Plan button link. Leave empty for /order/{slug}. Or set #contact-modal / any URL.
   */
  ctaHref?: string | null;
  /**
   * Subtitle on the order page under the plan title
   */
  subtitle?: string | null;
  /**
   * Green promo callout on the order page
   */
  promo?: string | null;
  /**
   * Detailed “what’s included in development” block on the order page (rich text). Shown last in the plan card.
   */
  includes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Text under the payment method selector on the order page
   */
  paymentNote?: string | null;
  /**
   * Tax rate under Taxes, e.g. "17%". Parsed as percent and added to the order total.
   */
  taxNote?: string | null;
  /**
   * Optional. Fixed tax amount (number) if taxNote has no %, or a label when tax is not calculated.
   */
  taxValue?: string | null;
  /**
   * Optional. If empty, defaults (pay in full / 12 payments when priceNote) are used.
   */
  periods?:
    | {
        /**
         * e.g. "full" or "12"
         */
        periodId: string;
        label: string;
        /**
         * 1 = one-time; 12 = split into months for display
         */
        months?: number | null;
        discountPercent?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional order extras (e.g. Monthly subscription). Pair with a Features row “Подписка: …” if the price should still show on homepage cards.
   */
  addons?:
    | {
        /**
         * Stable id, e.g. "priority-support"
         */
        addonId: string;
        name: string;
        description?: string | null;
        /**
         * Per locale, same format as Feature Value — e.g. en "350₪/mth", ru "350₪/мес", he "₪350/חודש"
         */
        priceDisplay: string;
        /**
         * Expandable details under the “Subscription: {price}” line on the order add-on card.
         */
        full?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Discount % for 1-month term (0 = no discount)
         */
        discountMonths1?: number | null;
        /**
         * Discount % for 6-month term (0 = no discount)
         */
        discountMonths6?: number | null;
        /**
         * Discount % for 12-month term (0 = no discount)
         */
        discountMonths12?: number | null;
        recommended?: boolean | null;
        /**
         * Always include this add-on. Customers cannot deselect it; subscription term (1/6/12) is hidden — price is charged as a single monthly rate.
         */
        mandatory?: boolean | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If empty, the page title and intro text are used for search engines and social previews.
   */
  seo?: {
    /**
     * Meta title. Example: "Design & Branding | Erythro.ai"
     */
    title?: string | null;
    /**
     * Meta description (recommended up to ~160 characters).
     */
    description?: string | null;
  };
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories for portfolio projects and the filter chips on /portfolio. Edit labels, add/remove items, and reorder here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  /**
   * Shown on filters and project cards (localized)
   */
  label: string;
  /**
   * Stable id used for filtering (e.g. "ai", "crm"). Prefer lowercase, no spaces. Changing this breaks existing project links until you re-save them.
   */
  value: string;
  /**
   * Sort order for filter chips (ascending)
   */
  order?: number | null;
  /**
   * Show this category in the /portfolio filter row
   */
  showInFilters?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects".
 */
export interface PortfolioProject {
  id: number;
  /**
   * URL segment, e.g. "ai-lead-qualifier" → /portfolio/ai-lead-qualifier
   */
  slug: string;
  title: string;
  /**
   * Pick from Portfolio Categories (Pages → Portfolio Categories). Edit that list to add/remove options.
   */
  category: number | PortfolioCategory;
  /**
   * Optional override for the label on cards/hero. Leave empty to use the category’s localized label.
   */
  categoryLabel?: string | null;
  /**
   * Short card description on /portfolio
   */
  description: string;
  /**
   * Hero summary on the project page (shown only in the hero). Rich text editor.
   */
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional text under the project title in the body section. Leave empty to hide. Rich text editor.
   */
  subtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "2025" or "2024 — 2025"
   */
  date?: string | null;
  client?: string | null;
  /**
   * Optional external project URL
   */
  link?: string | null;
  stack?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Thumbnail on the portfolio grid
   */
  cardImage?: (number | null) | Media;
  /**
   * Full-bleed hero image or video (desktop)
   */
  heroMedia?: (number | null) | Media;
  /**
   * Hero image or video for mobile (<1024px). Prefer 1080×1920 (9:16). Falls back to desktop hero if empty.
   */
  heroMediaMobile?: (number | null) | Media;
  body?:
    | {
        heading?: string | null;
        paragraphs?:
          | {
              /**
               * Body paragraph (rich text)
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If empty, the page title and intro text are used for search engines and social previews.
   */
  seo?: {
    /**
     * Meta title. Example: "Design & Branding | Erythro.ai"
     */
    title?: string | null;
    /**
     * Meta description (recommended up to ~160 characters).
     */
    description?: string | null;
  };
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Optional external link
   */
  url?: string | null;
  /**
   * Sort order (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Click Open or the name to view the full order / inquiry. Use sidebar filters: Solution Orders, AI Audit Orders, Contact Inquiries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  /**
   * Intake channel (set by the site form; do not change manually)
   */
  source?: ('order' | 'audit' | 'contact') | null;
  /**
   * Site language the visitor used
   */
  locale?: string | null;
  /**
   * Client IP address at intake time
   */
  ip?: string | null;
  /**
   * Ordered plan slug from checkout (solutions or audit plans)
   */
  planSlug?: string | null;
  /**
   * Displayed order total at checkout
   */
  planTotal?: string | null;
  /**
   * Audited site URL (AI Audit checkout only)
   */
  website?: string | null;
  /**
   * Preferred report language (AI Audit)
   */
  auditLanguage?: ('en' | 'ru' | 'he') | null;
  /**
   * Pipeline: new → in_progress → report_sent; failed after max retries (manual review)
   */
  auditStatus?: ('new' | 'in_progress' | 'report_sent' | 'failed') | null;
  /**
   * Final audit score (0–100)
   */
  auditScore?: number | null;
  /**
   * Structured LLM findings (JSON)
   */
  auditSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PDF / HTML object URL in Cloudflare R2
   */
  reportUrl?: string | null;
  /**
   * Inline HTML report for typical sizes (≤ ~2MB); larger reports stay in R2 only
   */
  htmlResult?: string | null;
  /**
   * Auto-restart attempts (n8n reconciliation)
   */
  retryCount?: number | null;
  /**
   * Last worker error (no Telegram in MVP — inspect in admin)
   */
  errorLast?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'solution-plans';
        value: number | SolutionPlan;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'portfolio-projects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              ctaText?: T;
              id?: T;
              blockName?: T;
            };
        wordStackBlock?:
          | T
          | {
              words?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  number?: T;
  image?: T;
  heroMedia?: T;
  currency?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  summary?: T;
  description?: T;
  offerings?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        pricePrefix?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-plans_select".
 */
export interface SolutionPlansSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  slug?: T;
  price?: T;
  currency?: T;
  pricePrefix?: T;
  originalPrice?: T;
  priceNote?: T;
  featured?: T;
  features?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  disclaimer?: T;
  ctaHref?: T;
  subtitle?: T;
  promo?: T;
  includes?: T;
  paymentNote?: T;
  taxNote?: T;
  taxValue?: T;
  periods?:
    | T
    | {
        periodId?: T;
        label?: T;
        months?: T;
        discountPercent?: T;
        id?: T;
      };
  addons?:
    | T
    | {
        addonId?: T;
        name?: T;
        description?: T;
        priceDisplay?: T;
        full?: T;
        discountMonths1?: T;
        discountMonths6?: T;
        discountMonths12?: T;
        recommended?: T;
        mandatory?: T;
        note?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  order?: T;
  showInFilters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  categoryLabel?: T;
  description?: T;
  summary?: T;
  subtitle?: T;
  date?: T;
  client?: T;
  link?: T;
  stack?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  cardImage?: T;
  heroMedia?: T;
  heroMediaMobile?: T;
  body?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  source?: T;
  locale?: T;
  ip?: T;
  planSlug?: T;
  planTotal?: T;
  website?: T;
  auditLanguage?: T;
  auditStatus?: T;
  auditScore?: T;
  auditSummary?: T;
  reportUrl?: T;
  htmlResult?: T;
  retryCount?: T;
  errorLast?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Top-level menu entries. Add Submenu Items under any row (Services, Solutions, etc.) to show a dropdown in the burger menu.
   */
  navItems?:
    | {
        label: string;
        /**
         * Subtitle under the burger-menu title (e.g. “What we can build for you”). Leave empty to hide.
         */
        description?: string | null;
        /**
         * Parent link target, e.g. #services, #solutions, /contacts. Clicking the parent still scrolls/navigates here when there is no submenu handler.
         */
        href: string;
        /**
         * Optional nested links shown under this item in the burger menu. Leave empty to hide the accordion (except Services/Solutions fallbacks from CMS collections).
         */
        children?:
          | {
              label: string;
              /**
               * e.g. /services/design, /order/business-automation, #cases
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary call-to-action label (Let’s Talk, etc.)
   */
  ctaLabel?: string | null;
  /**
   * Link for the Let’s Talk / primary CTA buttons. Default #contact-modal opens the contact form.
   */
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  preHeading?: string | null;
  mainHeading?: string | null;
  subtext?: string | null;
  /**
   * "Find out more" button label
   */
  ctaFind?: string | null;
  /**
   * Find out more link. Default #contacts (mobile → contacts, desktop → Let’s Talk scroll). Use #contact-modal for the form, or any URL/path.
   */
  ctaHref?: string | null;
  /**
   * Desktop hero background (video or image, ≥1024px). Kept as-is on large screens.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Mobile hero background image (<1024px). Prefer a still frame / photo so mobile does not download the desktop video. Recommended 1080×1920 (9:16), WebP/JPG ~200–400 KB. Falls back to desktop media if empty.
   */
  backgroundImageMobile?: (number | null) | Media;
  /**
   * Rotating hero headlines on the home page. Each phrase has a solid main line and an optional large background outline. Edit per locale (en / ru / he). Need at least 2 phrases.
   */
  words?:
    | {
        /**
         * Solid foreground headline (the text that settles into the hero title).
         */
        word: string;
        /**
         * Large outline text behind the main headline. Leave empty to reuse the main text.
         */
        outline?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section".
 */
export interface ServicesSection {
  id: number;
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  startCTA?: string | null;
  /**
   * Link for the services “start” CTA when used.
   */
  startCtaHref?: string | null;
  priceLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  preTitle?: string | null;
  subtitle?: string | null;
  cardTitle?: string | null;
  cardCategory?: string | null;
  cardDescription?: string | null;
  cardCTA?: string | null;
  /**
   * Optional link for the card CTA label (if shown).
   */
  cardCtaHref?: string | null;
  /**
   * Text link under the video banner, e.g. "View All Projects" (arrows are added in UI)
   */
  viewAllProjects?: string | null;
  /**
   * Banner + “View all projects” link. Default /portfolio.
   */
  viewAllHref?: string | null;
  /**
   * Desktop banner video (1024px+). Shown instead of the static default when set.
   */
  bannerVideo?: (number | null) | Media;
  /**
   * Mobile banner video (under 1024px). Falls back to the desktop video when empty.
   */
  bannerVideoMobile?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-section".
 */
export interface SolutionsSection {
  id: number;
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  ctaLabel?: string | null;
  /**
   * Optional override for all plan buttons. Leave empty to use each plan’s own link (or /order/{slug}).
   */
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home page FAQ: section headings and accordion Q&A (localized en / ru / he).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section".
 */
export interface FaqSection {
  id: number;
  /**
   * Main FAQ heading, e.g. "FAQ"
   */
  sectionTitle?: string | null;
  /**
   * Short line under the title
   */
  sectionSubtitle?: string | null;
  /**
   * Accordion items on the home page. Drag to reorder. Switch locale in the admin bar to edit translations.
   */
  items?:
    | {
        question: string;
        /**
         * Answer shown when the accordion item is open (bold, lists, links, etc.)
         */
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  ctaHeadingLine1?: string | null;
  ctaHeadingLine2?: string | null;
  ctaButton?: string | null;
  /**
   * Footer CTA button link. Default #contact-modal opens the contact form.
   */
  ctaHref?: string | null;
  companyTitle?: string | null;
  companyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactTitle?: string | null;
  emailLabel?: string | null;
  phoneLabel?: string | null;
  locationLabel?: string | null;
  locationValue?: string | null;
  copyright?: string | null;
  legalLinks?:
    | {
        /**
         * Stable id, e.g. privacy
         */
        key?: string | null;
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Address book for the site. Use the dropdowns below to choose display and form notification targets. Outgoing mail still sends from Hostinger order@erythro.ai.
   */
  emails?:
    | {
        /**
         * e.g. Orders, Privacy, General
         */
        label?: string | null;
        address: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy single email — synced from Display email (footer).
   */
  email?: string | null;
  /**
   * Shown in the site footer.
   */
  displayEmailFooter?: string | null;
  /**
   * Shown on /contacts.
   */
  displayEmailContacts?: string | null;
  /**
   * Used on legal pages and in the contact-form privacy notice (replaces the hardcoded address in copy).
   */
  displayEmailLegal?: string | null;
  /**
   * Contacts page form and general “Leave a message” modal.
   */
  notifyEmailContact?: string | null;
  /**
   * CTAs from Solutions section and /order/[slug].
   */
  notifyEmailOrder?: string | null;
  /**
   * Raw phone for tel: link, e.g. +972509312746
   */
  phone?: string | null;
  /**
   * Formatted phone shown to users
   */
  phoneDisplay?: string | null;
  /**
   * Facebook URL
   */
  facebook?: string | null;
  /**
   * Telegram URL (e.g. https://t.me/your_channel)
   */
  telegram?: string | null;
  cookieMessage?: string | null;
  cookieAccept?: string | null;
  cookieDecline?: string | null;
  /**
   * Document / Open Graph title (per locale)
   */
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Social share image (1200x630 recommended)
   */
  ogImage?: (number | null) | Media;
  /**
   * /contacts — Recommended: 1920×150 px. Images keep original quality. Video (MP4/WebM) autoplays muted.
   */
  contactsHeroMedia?: (number | null) | Media;
  /**
   * /portfolio — Recommended: 1920×150 px. Images keep original quality. Video (MP4/WebM) autoplays muted.
   */
  portfolioHeroMedia?: (number | null) | Media;
  /**
   * Legal pages (privacy, terms, accessibility) — Recommended: 1920×150 px.
   */
  legalHeroMedia?: (number | null) | Media;
  /**
   * /order/[slug] — Recommended: 1920×150 px.
   */
  orderHeroMedia?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-privacy".
 */
export interface LegalPrivacy {
  id: number;
  /**
   * Page heading shown to visitors
   */
  title: string;
  /**
   * SEO meta description (~155 chars)
   */
  metaDescription?: string | null;
  /**
   * Date shown as "Last updated" (e.g. 2026-07-29 or 29.07.2026). One date for all locales — not overwritten on save.
   */
  statementDate?: string | null;
  /**
   * Introductory paragraph shown before the first section
   */
  intro?: string | null;
  /**
   * Page sections. Each section has a heading, body text (one paragraph per line), and optional bullets (one item per line).
   */
  sections?:
    | {
        /**
         * Section heading, e.g. "1. Data controller"
         */
        heading: string;
        /**
         * Body paragraphs — one paragraph per line. Empty lines are ignored.
         */
        paragraphs?: string | null;
        /**
         * Bullet list items — one item per line. Leave empty if no bullets.
         */
        bullets?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional closing line at the bottom (e.g. contact info)
   */
  closing?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-terms".
 */
export interface LegalTerm {
  id: number;
  /**
   * Page heading shown to visitors
   */
  title: string;
  /**
   * SEO meta description (~155 chars)
   */
  metaDescription?: string | null;
  /**
   * Date shown as "Last updated" (e.g. 2026-07-29 or 29.07.2026). One date for all locales — not overwritten on save.
   */
  statementDate?: string | null;
  /**
   * Introductory paragraph shown before the first section
   */
  intro?: string | null;
  /**
   * Page sections. Each section has a heading, body text (one paragraph per line), and optional bullets (one item per line).
   */
  sections?:
    | {
        /**
         * Section heading, e.g. "1. Data controller"
         */
        heading: string;
        /**
         * Body paragraphs — one paragraph per line. Empty lines are ignored.
         */
        paragraphs?: string | null;
        /**
         * Bullet list items — one item per line. Leave empty if no bullets.
         */
        bullets?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional closing line at the bottom (e.g. contact info)
   */
  closing?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-accessibility".
 */
export interface LegalAccessibility {
  id: number;
  /**
   * Page heading shown to visitors
   */
  title: string;
  /**
   * SEO meta description (~155 chars)
   */
  metaDescription?: string | null;
  /**
   * Date shown as "Last updated" (e.g. 2026-07-29 or 29.07.2026). One date for all locales — not overwritten on save.
   */
  statementDate?: string | null;
  /**
   * Introductory paragraph shown before the first section
   */
  intro?: string | null;
  /**
   * Page sections. Each section has a heading, body text (one paragraph per line), and optional bullets (one item per line).
   */
  sections?:
    | {
        /**
         * Section heading, e.g. "1. Data controller"
         */
        heading: string;
        /**
         * Body paragraphs — one paragraph per line. Empty lines are ignored.
         */
        paragraphs?: string | null;
        /**
         * Bullet list items — one item per line. Leave empty if no bullets.
         */
        bullets?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional closing line at the bottom (e.g. contact info)
   */
  closing?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-page".
 */
export interface AuditPage {
  id: number;
  /**
   * Page <title> and H1
   */
  title: string;
  /**
   * SEO meta description (~155 chars)
   */
  metaDescription?: string | null;
  /**
   * Labels shown in the audit page tab navigation
   */
  tabs?: {
    audit?: string | null;
    how?: string | null;
    pricing?: string | null;
  };
  form?: {
    heading?: string | null;
    intro?: string | null;
    /**
     * Short note under the intro (rate-limit hint)
     */
    introNote?: string | null;
    /**
     * "Required field" label
     */
    requiredNote?: string | null;
    website?: string | null;
    websitePlaceholder?: string | null;
    /**
     * Validation error for invalid URL
     */
    websiteInvalid?: string | null;
    auditLanguage?: string | null;
    /**
     * Labels for each report-language option in every UI locale. E.g. the EN option reads "English" in EN, "Английский" in RU, "אנגלית" in HE.
     */
    auditLanguageOptions?: {
      en?: string | null;
      ru?: string | null;
      he?: string | null;
    };
    submit?: string | null;
    success?: string | null;
  };
  how?: {
    kicker?: string | null;
    heroTitle?: string | null;
    heroIntro?: string | null;
    stats?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    stepsHeading?: string | null;
    steps?:
      | {
          label?: string | null;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    methodologyTitle?: string | null;
    /**
     * Suffix after the weight value, e.g. "of the score"
     */
    weightNote?: string | null;
    methodologyIntro?: string | null;
    pillars?:
      | {
          /**
           * Non-localized weight value, e.g. "27%"
           */
          weight?: string | null;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    categoriesTitle?: string | null;
    categoriesIntro?: string | null;
    categories?:
      | {
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    principlesTitle?: string | null;
    principles?:
      | {
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricing?: {
    kicker?: string | null;
    title?: string | null;
    intro?: string | null;
    footnote?: string | null;
    agency?: string | null;
    agencyCta?: string | null;
    plans?:
      | {
          /**
           * Stable plan id, e.g. "free", "diagnostic", "pro", "delegate"
           */
          planId: string;
          featured?: boolean | null;
          name?: string | null;
          price?: string | null;
          /**
           * Struck-through comparison price (optional)
           */
          priceCompare?: string | null;
          /**
           * Short note under price, e.g. "one-time · promo"
           */
          priceNote?: string | null;
          /**
           * Short plan description (optional)
           */
          description?: string | null;
          features?:
            | {
                feature: string;
                id?: string | null;
              }[]
            | null;
          cta?: string | null;
          /**
           * Link target: /portfolio, #contacts, #services, or #contact-modal (opens the contact form).
           */
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        description?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  subtext?: T;
  ctaFind?: T;
  ctaHref?: T;
  backgroundImage?: T;
  backgroundImageMobile?: T;
  words?:
    | T
    | {
        word?: T;
        outline?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section_select".
 */
export interface ServicesSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  startCTA?: T;
  startCtaHref?: T;
  priceLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  preTitle?: T;
  subtitle?: T;
  cardTitle?: T;
  cardCategory?: T;
  cardDescription?: T;
  cardCTA?: T;
  cardCtaHref?: T;
  viewAllProjects?: T;
  viewAllHref?: T;
  bannerVideo?: T;
  bannerVideoMobile?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-section_select".
 */
export interface SolutionsSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section_select".
 */
export interface FaqSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaHeadingLine1?: T;
  ctaHeadingLine2?: T;
  ctaButton?: T;
  ctaHref?: T;
  companyTitle?: T;
  companyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactTitle?: T;
  emailLabel?: T;
  phoneLabel?: T;
  locationLabel?: T;
  locationValue?: T;
  copyright?: T;
  legalLinks?:
    | T
    | {
        key?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  emails?:
    | T
    | {
        label?: T;
        address?: T;
        id?: T;
      };
  email?: T;
  displayEmailFooter?: T;
  displayEmailContacts?: T;
  displayEmailLegal?: T;
  notifyEmailContact?: T;
  notifyEmailOrder?: T;
  phone?: T;
  phoneDisplay?: T;
  facebook?: T;
  telegram?: T;
  cookieMessage?: T;
  cookieAccept?: T;
  cookieDecline?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  contactsHeroMedia?: T;
  portfolioHeroMedia?: T;
  legalHeroMedia?: T;
  orderHeroMedia?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-privacy_select".
 */
export interface LegalPrivacySelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  statementDate?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        paragraphs?: T;
        bullets?: T;
        id?: T;
      };
  closing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-terms_select".
 */
export interface LegalTermsSelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  statementDate?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        paragraphs?: T;
        bullets?: T;
        id?: T;
      };
  closing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-accessibility_select".
 */
export interface LegalAccessibilitySelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  statementDate?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        paragraphs?: T;
        bullets?: T;
        id?: T;
      };
  closing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-page_select".
 */
export interface AuditPageSelect<T extends boolean = true> {
  title?: T;
  metaDescription?: T;
  tabs?:
    | T
    | {
        audit?: T;
        how?: T;
        pricing?: T;
      };
  form?:
    | T
    | {
        heading?: T;
        intro?: T;
        introNote?: T;
        requiredNote?: T;
        website?: T;
        websitePlaceholder?: T;
        websiteInvalid?: T;
        auditLanguage?: T;
        auditLanguageOptions?:
          | T
          | {
              en?: T;
              ru?: T;
              he?: T;
            };
        submit?: T;
        success?: T;
      };
  how?:
    | T
    | {
        kicker?: T;
        heroTitle?: T;
        heroIntro?: T;
        stats?:
          | T
          | {
              label?: T;
              id?: T;
            };
        stepsHeading?: T;
        steps?:
          | T
          | {
              label?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        methodologyTitle?: T;
        weightNote?: T;
        methodologyIntro?: T;
        pillars?:
          | T
          | {
              weight?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        categoriesTitle?: T;
        categoriesIntro?: T;
        categories?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        principlesTitle?: T;
        principles?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        kicker?: T;
        title?: T;
        intro?: T;
        footnote?: T;
        agency?: T;
        agencyCta?: T;
        plans?:
          | T
          | {
              planId?: T;
              featured?: T;
              name?: T;
              price?: T;
              priceCompare?: T;
              priceNote?: T;
              description?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              cta?: T;
              ctaHref?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}